// ============ THE FORGE — electronics: pin map, schematic, wiring ============
// ESP32-S3-DevKitC-1 GPIO budget, deterministic assignment from the spec.

// Pin budget avoids ESP32-S3 strapping pins (0/3/45/46), USB D± (19/20) and
// the octal-PSRAM pins reserved on the N8R2 module (35–37). Rev-2 fix — the
// validation engine (js/validation.js) enforces this permanently.
const ROW_PINS = [4, 5, 6, 7, 15];
const COL_PINS = [16, 17, 18, 8, 9, 10];
const ENC_PINS = [[11, 12, 13], [14, 21, 47], [48, 38, 39], [40, 41, 42]];
const PEDAL_PINS = [33, 34, 3, 26];   // GPIO3 = strapping (OK as pulled-up input, flagged); 26 flagged on some modules
const I2C = { sda: 1, scl: 2 };

export function buildElectronics(spec) {
  const m = spec.modules;
  const mtx = spec.derived.matrix;
  const rows = Math.min(mtx.rows, ROW_PINS.length);
  const cols = Math.min(mtx.cols, COL_PINS.length);
  const e = {
    mcu: "ESP32-S3-DevKitC-1",
    matrix: {
      rows: ROW_PINS.slice(0, rows),
      cols: COL_PINS.slice(0, cols),
      keys: mtx.keys,
      diodes: mtx.keys.length,
    },
    encoders: Array.from({ length: m.encoders.count }, (_, i) => ({
      label: `ENC${i + 1}`, a: ENC_PINS[i][0], b: ENC_PINS[i][1], sw: ENC_PINS[i][2],
    })),
    i2c: [],
    pedals: Array.from({ length: m.pedals.count }, (_, i) => ({ label: `PEDAL${i + 1}`, pin: PEDAL_PINS[i] })),
    power: { vcc: "3V3", gnd: "GND", usb: "Native USB (GPIO19/20 internal)" },
  };
  if (m.oled.present) e.i2c.push({ label: "OLED SSD1306", addr: "0x3C" });
  if (m.trackball.present) e.i2c.push({ label: "Trackball PIM447", addr: "0x0A" });
  if (e.i2c.length) e.i2cPins = I2C;
  spec.derived.elec = e;
  return e;
}

// ---------------------------------------------------------------- schematic SVG
export function schematicSVG(spec) {
  const e = spec.derived.elec;
  const W = 980, H = 640;
  let s = svgOpen(W, H);
  s += `<style>
    .blk{fill:#171c24;stroke:#3a4250;stroke-width:1.4;rx:8}
    .mcu{fill:#101720;stroke:#ff7a1a;stroke-width:1.6}
    .t{fill:#e8e4da;font:12.5px monospace}
    .tt{fill:#ffb143;font:bold 13px monospace}
    .pin{fill:#9aa0aa;font:10.5px monospace}
    .net{stroke:#6fb7ff;stroke-width:1.2;fill:none}
    .net2{stroke:#a8d08d;stroke-width:1.2;fill:none}
    .net3{stroke:#ffb143;stroke-width:1.2;fill:none}
    .lbl{fill:#5f6b7d;font:9.5px monospace}
  </style>`;
  s += `<text x="18" y="26" class="tt">${esc(spec.name)} — SCHEMATIC  (rev ${spec.rev})</text>`;
  s += `<text x="18" y="42" class="lbl">Generated by THE FORGE · ${e.mcu} · all switches to GND, internal pull-ups</text>`;

  // MCU
  const mx = 400, my = 90, mw = 190, mh = 460;
  s += `<rect x="${mx}" y="${my}" width="${mw}" height="${mh}" class="mcu" rx="10"/>`;
  s += `<text x="${mx + mw / 2}" y="${my + 24}" class="tt" text-anchor="middle">ESP32-S3</text>`;
  s += `<text x="${mx + mw / 2}" y="${my + 40}" class="lbl" text-anchor="middle">DevKitC-1 · native USB HID</text>`;

  let ly = my + 66, ry = my + 66;
  const lpin = (name, net) => { s += `<line x1="${mx - 10}" y1="${ly}" x2="${mx}" y2="${ly}" class="net"/><text x="${mx + 8}" y="${ly + 4}" class="pin">${name}</text>`; const y = ly; ly += 21; return y; };
  const rpin = (name, cls = "net2") => { s += `<line x1="${mx + mw}" y1="${ry}" x2="${mx + mw + 10}" y2="${ry}" class="${cls}"/><text x="${mx + mw - 8}" y="${ry + 4}" class="pin" text-anchor="end">${name}</text>`; const y = ry; ry += 21; return y; };

  // -------- left: key matrix --------
  const rowsN = e.matrix.rows.length, colsN = e.matrix.cols.length;
  const kx = 60, ky = 120, kw = 250, kh = 40 + rowsN * 34;
  s += `<rect x="${kx}" y="${ky}" width="${kw}" height="${kh}" class="blk" rx="8"/>`;
  s += `<text x="${kx + 12}" y="${ky + 20}" class="t">KEY MATRIX ${rowsN}×${colsN}</text>`;
  s += `<text x="${kx + 12}" y="${ky + 36}" class="lbl">${e.matrix.keys.length} keys · 1N4148 per key (COL2ROW)</text>`;
  // little matrix glyph
  for (let r = 0; r < rowsN; r++) for (let c = 0; c < Math.min(colsN, 6); c++) {
    const gx = kx + 24 + c * 34, gy = ky + 52 + r * 34;
    s += `<rect x="${gx}" y="${gy}" width="18" height="14" fill="none" stroke="#4a5568" rx="2"/>`;
    s += `<line x1="${gx + 4}" y1="${gy + 14}" x2="${gx + 14}" y2="${gy}" stroke="#4a5568"/>`;
  }
  for (let r = 0; r < rowsN; r++) {
    const py = lpin(`GPIO${e.matrix.rows[r]}  ROW${r}`);
    s += `<path class="net" d="M ${kx + kw} ${ky + 58 + r * 34} H ${mx - 40 - r * 6} V ${py} H ${mx - 10}"/>`;
  }
  for (let c = 0; c < colsN; c++) {
    const py = lpin(`GPIO${e.matrix.cols[c]}  COL${c}`);
    s += `<path class="net" d="M ${kx + 30 + c * 34} ${ky + kh} V ${ky + kh + 14 + c * 5} H ${mx - 70 - c * 5} V ${py} H ${mx - 10}"/>`;
  }

  // -------- left: pedals --------
  if (e.pedals.length) {
    const px = 60, py0 = ky + kh + 60;
    s += `<rect x="${px}" y="${py0}" width="250" height="${34 + e.pedals.length * 24}" class="blk" rx="8"/>`;
    s += `<text x="${px + 12}" y="${py0 + 20}" class="t">FOOT PEDALS (3.5 mm TRS)</text>`;
    e.pedals.forEach((p, i) => {
      const yy = py0 + 40 + i * 24;
      s += `<circle cx="${px + 24}" cy="${yy}" r="6" fill="none" stroke="#4a5568"/><text x="${px + 40}" y="${yy + 4}" class="pin">${p.label}</text>`;
      const mp = lpin(`GPIO${p.pin}  ${p.label}`);
      s += `<path class="net" d="M ${px + 250} ${yy} H ${mx - 30 - i * 8} V ${mp} H ${mx - 10}"/>`;
    });
  }

  // -------- right: I2C bus --------
  let bx = 700;
  if (e.i2c.length) {
    const sdaY = rpin(`GPIO${e.i2cPins.sda}  SDA`, "net3");
    const sclY = rpin(`GPIO${e.i2cPins.scl}  SCL`, "net3");
    s += `<path class="net3" d="M ${mx + mw + 10} ${sdaY} H ${bx - 30}"/>`;
    s += `<path class="net3" d="M ${mx + mw + 10} ${sclY} H ${bx - 30}"/>`;
    s += `<text x="${bx - 60}" y="${sdaY - 6}" class="lbl">I²C 400 kHz · 4.7 kΩ pull-ups</text>`;
    e.i2c.forEach((d, i) => {
      const yy = 100 + i * 84;
      s += `<rect x="${bx}" y="${yy}" width="230" height="64" class="blk" rx="8"/>`;
      s += `<text x="${bx + 12}" y="${yy + 24}" class="t">${d.label}</text>`;
      s += `<text x="${bx + 12}" y="${yy + 44}" class="lbl">addr ${d.addr} · 3V3 · GND</text>`;
      s += `<path class="net3" d="M ${bx - 30} ${sdaY} V ${yy + 32} H ${bx}"/>`;
      s += `<path class="net3" d="M ${bx - 30 + 6} ${sclY} V ${yy + 46} H ${bx}"/>`;
    });
  }
  // -------- right: encoders --------
  e.encoders.forEach((en, i) => {
    const yy = 290 + i * 92;
    s += `<rect x="${bx}" y="${yy}" width="230" height="76" class="blk" rx="8"/>`;
    s += `<circle cx="${bx + 34}" cy="${yy + 38}" r="18" fill="none" stroke="#4a5568"/><line x1="${bx + 34}" y1="${yy + 24}" x2="${bx + 34}" y2="${yy + 32}" stroke="#4a5568"/>`;
    s += `<text x="${bx + 64}" y="${yy + 26}" class="t">${en.label} — PEC11R</text>`;
    s += `<text x="${bx + 64}" y="${yy + 44}" class="lbl">A→${en.a}  B→${en.b}  SW→${en.sw}</text>`;
    s += `<text x="${bx + 64}" y="${yy + 60}" class="lbl">common → GND</text>`;
    const pa = rpin(`GPIO${en.a}  ${en.label}A`);
    const pb = rpin(`GPIO${en.b}  ${en.label}B`);
    const ps = rpin(`GPIO${en.sw} ${en.label}SW`);
    s += `<path class="net2" d="M ${mx + mw + 10} ${pa} H ${bx - 20 - i * 6} V ${yy + 22} H ${bx}"/>`;
    s += `<path class="net2" d="M ${mx + mw + 10} ${pb} H ${bx - 26 - i * 6} V ${yy + 38} H ${bx}"/>`;
    s += `<path class="net2" d="M ${mx + mw + 10} ${ps} H ${bx - 32 - i * 6} V ${yy + 54} H ${bx}"/>`;
  });

  s += `</svg>`;
  return s;
}

// ---------------------------------------------------------------- wiring SVG
export function wiringSVG(spec) {
  const { deck, parts, jacks, usb } = spec.derived;
  const e = spec.derived.elec;
  const pad = 60, scale = 3.1;
  const W = deck.w * scale + pad * 2 + 240, H = deck.d * scale + pad * 2 + 40;
  const X = x => pad + 120 + (x + deck.w / 2) * scale;
  const Y = y => pad + (deck.d / 2 - y) * scale;
  let s = svgOpen(W, H);
  s += `<style>
    .t{fill:#e8e4da;font:12px monospace}.tt{fill:#ffb143;font:bold 13px monospace}
    .lbl{fill:#8b93a2;font:9.5px monospace}
    .w1{stroke:#6fb7ff;stroke-width:1.5;fill:none;opacity:.9}
    .w2{stroke:#a8d08d;stroke-width:1.5;fill:none;opacity:.9}
    .w3{stroke:#ffb143;stroke-width:1.5;fill:none;opacity:.9}
    .w4{stroke:#ff6b7e;stroke-width:1.5;fill:none;opacity:.9}
  </style>`;
  s += `<text x="16" y="26" class="tt">${esc(spec.name)} — INTERNAL WIRING (top view, plate removed)</text>`;
  // deck outline
  s += `<rect x="${X(-deck.w / 2)}" y="${Y(deck.d / 2)}" width="${deck.w * scale}" height="${deck.d * scale}" rx="${deck.r * scale}" fill="#141920" stroke="#3a4250" stroke-width="2"/>`;
  // MCU
  const mX = X(usb.x), mY = Y(deck.d / 2 - 32);
  s += `<rect x="${mX - 34}" y="${mY - 60}" width="68" height="110" rx="6" fill="#101720" stroke="#ff7a1a"/>`;
  s += `<text x="${mX}" y="${mY - 12}" class="t" text-anchor="middle">ESP32-S3</text>`;
  s += `<rect x="${mX - 12}" y="${Y(deck.d / 2) - 8}" width="24" height="12" fill="#59636f"/><text x="${mX}" y="${Y(deck.d / 2) - 14}" class="lbl" text-anchor="middle">USB-C</text>`;

  for (const p of parts) {
    const px = X(p.x), py = Y(p.y);
    if (p.type === "key") {
      s += `<rect x="${px - 20}" y="${py - 20}" width="40" height="40" rx="4" transform="rotate(${-p.rot} ${px} ${py})" fill="#1d232c" stroke="#4a5568"/>`;
      s += `<text x="${px}" y="${py + 4}" class="lbl" text-anchor="middle">${p.label}</text>`;
      s += `<path class="w1" d="M ${px} ${py} Q ${(px + mX) / 2} ${py - 14} ${mX - 30} ${mY - 40 + ((p.mr ?? 0) * 8)}"/>`;
    } else if (p.type === "encoder") {
      s += `<circle cx="${px}" cy="${py}" r="26" fill="#1d232c" stroke="#4a5568"/><text x="${px}" y="${py + 4}" class="lbl" text-anchor="middle">${p.label}</text>`;
      s += `<path class="w2" d="M ${px} ${py + 20} Q ${px} ${mY} ${mX + 34} ${mY - 20}"/>`;
    } else if (p.type === "trackball") {
      s += `<circle cx="${px}" cy="${py}" r="${(p.d / 2 + 6) * scale / 2.2}" fill="#26130f" stroke="#c9463d"/><text x="${px}" y="${py + 4}" class="lbl" text-anchor="middle">TB · I²C</text>`;
      s += `<path class="w3" d="M ${px} ${py} Q ${px + 40} ${mY + 30} ${mX - 34} ${mY + 10}"/>`;
    } else if (p.type === "oled") {
      s += `<rect x="${px - 40}" y="${py - 22}" width="80" height="44" rx="4" fill="#0f1a26" stroke="#6fb7ff"/><text x="${px}" y="${py + 4}" class="lbl" text-anchor="middle">OLED · I²C</text>`;
      s += `<path class="w3" d="M ${px + 40} ${py} Q ${(px + mX) / 2} ${py} ${mX - 34} ${mY - 10}"/>`;
    }
  }
  for (const j of jacks) {
    const jx = X(j.x), jy = Y(j.y);
    s += `<circle cx="${jx}" cy="${jy}" r="9" fill="#1d232c" stroke="#8b93a2"/><text x="${jx}" y="${jy - 14}" class="lbl" text-anchor="middle">${j.label}</text>`;
    s += `<path class="w4" d="M ${jx} ${jy} Q ${jx} ${mY + 44} ${mX + 34} ${mY + 30}"/>`;
  }
  // legend
  const lx = 16, lyy = 60;
  const leg = [["w1", "Matrix rows/cols → GPIO"], ["w2", "Encoder A/B/SW → GPIO"], ["w3", "I²C bus (SDA 1 / SCL 2)"], ["w4", `Pedal jacks → GPIO ${e.pedals.map(p => p.pin).join("/") || "—"}`]];
  leg.forEach(([cls, txt], i) => {
    s += `<line x1="${lx}" y1="${lyy + i * 22}" x2="${lx + 34}" y2="${lyy + i * 22}" class="${cls}"/>`;
    s += `<text x="${lx + 42}" y="${lyy + i * 22 + 4}" class="lbl">${txt}</text>`;
  });
  s += `</svg>`;
  return s;
}

function svgOpen(w, h) {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}" width="${w}" height="${h}" style="background:#0b0d10">`;
}
export function esc(t) { return String(t).replace(/&/g, "&amp;").replace(/</g, "&lt;"); }
