"use client";

import { useEffect, useMemo, useState, type FormEvent, type ComponentType } from "react";
import { useRouter } from "next/navigation";
import {
  AlertTriangle, Archive, BarChart3, Bell, BookOpen, CalendarDays,
  Check, CheckCircle2, ChevronRight, CircleDot, Database, FilePlus2,
  FileText, Gauge, Lightbulb, ListChecks, LogOut, Menu,
  Pin, Plus, Radar, RefreshCw, Search, Settings, ShieldCheck, Sparkles, Target,
  TrendingUp, Users, X, Zap,
} from "lucide-react";
import type { DashboardData, DashboardRecord } from "@/lib/dashboard";
import { patchJson, postJson } from "@/lib/api";
import { MarkdownRenderer } from "@/components/dashboard/MarkdownRenderer";

type View = "overview" | "briefs" | "opportunities" | "actions" | "intelligence" | "risks" | "ideas" | "analytics" | "sources" | "settings";
type Icon = ComponentType<{ size?: number; className?: string }>;
type UpdateRecord = (collection: keyof DashboardData, entity: string, id: string, changes: Record<string, unknown>) => Promise<void>;

const nav: { id: View; label: string; icon: Icon }[] = [
  { id: "overview", label: "Overview", icon: Gauge }, { id: "briefs", label: "Daily Briefs", icon: FileText },
  { id: "opportunities", label: "Opportunities", icon: Target }, { id: "actions", label: "Action Center", icon: ListChecks },
  { id: "intelligence", label: "Intelligence", icon: Radar }, { id: "risks", label: "Risks", icon: AlertTriangle },
  { id: "ideas", label: "Ideas", icon: Lightbulb }, { id: "analytics", label: "Analytics", icon: BarChart3 },
  { id: "sources", label: "Sources", icon: BookOpen }, { id: "settings", label: "Settings", icon: Settings },
];

const str = (value: unknown, fallback = "") => typeof value === "string" ? value : fallback;
const num = (value: unknown) => typeof value === "number" ? value : Number(value) || 0;
const bool = (value: unknown) => value === true;
const date = (value: unknown) => value ? new Date(String(value)).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" }) : "Not set";
const relatedTitle = (record: DashboardRecord) => str((record.briefs as { title?: unknown } | null)?.title, "Manual entry");
const tone = (value: string) => value === "critical" ? "border-red-400/30 bg-red-400/10 text-red-200" : value === "high" ? "border-amber-400/30 bg-amber-400/10 text-amber-200" : value === "completed" || value === "launched" || value === "mitigated" ? "border-emerald-400/30 bg-emerald-400/10 text-emerald-200" : "border-white/10 bg-white/[0.04] text-white/55";

function Badge({ value }: { value: string }) {
  return <span className={`inline-flex items-center rounded-full border px-2.5 py-1 font-mono text-[0.56rem] uppercase tracking-[0.14em] ${tone(value)}`}>{value.replaceAll("_", " ")}</span>;
}

function Empty({ icon: Icon = Database, title, body, action }: { icon?: Icon; title: string; body: string; action?: React.ReactNode }) {
  return <div className="card flex min-h-56 flex-col items-center justify-center p-8 text-center"><Icon size={28} className="text-white/25" /><h3 className="display mt-4 text-lg">{title}</h3><p className="mt-2 max-w-md text-sm leading-6 text-white/45">{body}</p>{action && <div className="mt-5">{action}</div>}</div>;
}

function Metric({ label, value, context, icon: Icon }: { label: string; value: string | number; context: string; icon: Icon }) {
  return <div className="card p-5"><div className="flex items-center justify-between"><span className="font-mono text-[0.58rem] uppercase tracking-label text-white/40">{label}</span><Icon size={16} className="text-crimson-light" /></div><div className="mt-4 font-mono text-3xl text-white">{value}</div><p className="mt-2 text-xs text-white/35">{context}</p></div>;
}

export function ExecutiveDashboard({ adminEmail, initialData }: { adminEmail: string; initialData: DashboardData }) {
  const router = useRouter();
  const [data, setData] = useState(initialData);
  const [view, setView] = useState<View>("overview");
  const [sidebar, setSidebar] = useState(false);
  const [command, setCommand] = useState(false);
  const [notifications, setNotifications] = useState(false);
  const [composer, setComposer] = useState<"brief" | "actions" | "opportunities" | "risks" | "ideas" | null>(null);
  const [working, setWorking] = useState<string | null>(null);
  const [message, setMessage] = useState<string | null>(null);

  useEffect(() => {
    const onKey = (event: KeyboardEvent) => {
      if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "k") { event.preventDefault(); setCommand(true); }
      if (event.key === "Escape") { setCommand(false); setNotifications(false); setComposer(null); }
    };
    window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey);
  }, []);

  const unreadBriefs = data.briefs.filter((r) => !bool(r.is_read) && !bool(r.is_archived)).length;
  const urgentActions = data.actions.filter((r) => ["critical", "high"].includes(str(r.priority)) && !["completed", "dismissed"].includes(str(r.status))).length;
  const newOpportunities = data.opportunities.filter((r) => str(r.stage) === "discovered").length;
  const activeRisks = data.risks.filter((r) => !["mitigated", "closed"].includes(str(r.status))).length;

  function replaceRecord(collection: keyof DashboardData, record: DashboardRecord) {
    setData((current) => ({ ...current, [collection]: (current[collection] as DashboardRecord[]).map((item) => item.id === record.id ? { ...item, ...record } : item) }));
  }

  async function update(collection: keyof DashboardData, entity: string, id: string, changes: Record<string, unknown>) {
    setWorking(id); setMessage(null);
    const response = await patchJson(`/api/dashboard/entities/${entity}/${id}`, changes);
    const payload = await response.json().catch(() => ({}));
    setWorking(null);
    if (!response.ok) { setMessage(payload.error ?? "Update failed."); return; }
    replaceRecord(collection, payload.record);
  }

  async function logout() { await postJson("/api/admin/logout"); router.push("/admin/login"); router.refresh(); }
  function openView(next: View) { setView(next); setSidebar(false); }
  function reload() { router.refresh(); }

  const title = nav.find((item) => item.id === view)?.label ?? "Overview";
  return (
    <div className="min-h-screen bg-base text-white">
      <div className="pointer-events-none fixed inset-0"><div className="absolute inset-0 bg-grid opacity-20" /><div className="absolute left-[30%] top-[-20%] h-[520px] w-[760px] rounded-full bg-crimson/[0.05] blur-[150px]" /></div>
      <aside className={`fixed inset-y-0 left-0 z-50 flex w-[270px] flex-col border-r border-white/10 bg-base-900/95 backdrop-blur-xl transition-transform lg:translate-x-0 ${sidebar ? "translate-x-0" : "-translate-x-full"}`}>
        <div className="flex h-20 items-center justify-between border-b border-white/10 px-5"><button onClick={() => openView("overview")} className="text-left"><span className="display block text-sm tracking-wide">REDMONT</span><span className="font-mono text-[0.5rem] uppercase tracking-[0.26em] text-crimson-light">Executive intelligence</span></button><button onClick={() => setSidebar(false)} className="p-2 text-white/50 lg:hidden" aria-label="Close navigation"><X size={18} /></button></div>
        <nav className="flex-1 space-y-1 overflow-y-auto p-3" aria-label="Dashboard navigation">{nav.map((item) => { const Icon = item.icon; const active = item.id === view; return <button key={item.id} onClick={() => openView(item.id)} aria-current={active ? "page" : undefined} className={`flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm transition-colors ${active ? "bg-crimson/15 text-white" : "text-white/48 hover:bg-white/[0.04] hover:text-white"}`}><Icon size={16} className={active ? "text-crimson-light" : ""} /><span>{item.label}</span>{item.id === "actions" && urgentActions > 0 && <span className="ml-auto rounded-full bg-crimson px-2 py-0.5 font-mono text-[0.55rem]">{urgentActions}</span>}</button>; })}</nav>
        <div className="border-t border-white/10 p-4">
          <a href="/admin" className="mb-3 flex w-full items-center gap-2 rounded-lg px-3 py-2 text-sm text-white/50 hover:bg-white/[0.04] hover:text-white">
            <Users size={15} /> Client console
          </a>
          <div className="mb-3 flex items-center gap-2 text-xs text-white/40"><ShieldCheck size={14} className="text-emerald-300" /><span className="truncate">{adminEmail}</span></div>
          <button onClick={logout} className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-sm text-white/50 hover:bg-white/[0.04] hover:text-white"><LogOut size={15} /> Secure logout</button>
        </div>
      </aside>

      {sidebar && <button className="fixed inset-0 z-40 bg-black/70 lg:hidden" aria-label="Close navigation" onClick={() => setSidebar(false)} />}
      <div className="relative lg:pl-[270px]">
        <header className="sticky top-0 z-30 flex h-20 items-center gap-4 border-b border-white/10 bg-base/85 px-4 backdrop-blur-xl sm:px-6 lg:px-8"><button onClick={() => setSidebar(true)} className="p-2 text-white/60 lg:hidden" aria-label="Open navigation"><Menu size={20} /></button><div><p className="font-mono text-[0.52rem] uppercase tracking-label text-white/35">RSG command center</p><h1 className="display text-lg">{title}</h1></div><div className="ml-auto flex items-center gap-2"><button onClick={() => setCommand(true)} className="hidden min-w-56 items-center gap-2 rounded-lg border border-white/10 bg-white/[0.025] px-3 py-2 text-left text-sm text-white/35 hover:border-white/20 sm:flex"><Search size={15} /><span>Search intelligence</span><kbd className="ml-auto rounded border border-white/10 px-1.5 font-mono text-[0.55rem]">⌘K</kbd></button><button onClick={() => setNotifications(true)} className="relative rounded-lg border border-white/10 p-2.5 text-white/55 hover:text-white" aria-label="Open notifications"><Bell size={17} />{data.notifications.some((n) => !bool(n.is_read)) && <span className="absolute right-2 top-2 h-1.5 w-1.5 rounded-full bg-crimson" />}</button><button onClick={reload} className="rounded-lg border border-white/10 p-2.5 text-white/55 hover:text-white" aria-label="Refresh dashboard"><RefreshCw size={17} /></button></div></header>

        <main className="mx-auto max-w-[1540px] p-4 sm:p-6 lg:p-8">
          {message && <div role="alert" className="mb-5 flex items-center justify-between rounded-lg border border-crimson/30 bg-crimson/10 px-4 py-3 text-sm text-crimson-light"><span>{message}</span><button onClick={() => setMessage(null)} aria-label="Dismiss"><X size={16} /></button></div>}
          {!data.configured || data.error ? <ConfigurationState error={data.error} /> : <>
            {view === "overview" && <Overview data={data} metrics={{ unreadBriefs, urgentActions, newOpportunities, activeRisks }} update={update} working={working} setView={openView} setComposer={setComposer} />}
            {view === "briefs" && <Briefs data={data} update={update} working={working} onCreate={() => setComposer("brief")} />}
            {view === "actions" && <Actions records={data.actions} update={update} working={working} onCreate={() => setComposer("actions")} />}
            {view === "opportunities" && <Opportunities records={data.opportunities} update={update} working={working} onCreate={() => setComposer("opportunities")} />}
            {view === "intelligence" && <Intelligence records={data.intelligence} />}
            {view === "risks" && <Risks records={data.risks} update={update} working={working} onCreate={() => setComposer("risks")} />}
            {view === "ideas" && <Ideas records={data.ideas} update={update} onCreate={() => setComposer("ideas")} />}
            {view === "analytics" && <Analytics data={data} />}
            {view === "sources" && <Sources records={data.sources} />}
            {view === "settings" && <SettingsPanel data={data} />}
          </>}
        </main>
      </div>

      {command && <CommandPalette data={data} onClose={() => setCommand(false)} onView={(v) => { openView(v); setCommand(false); }} onCreate={(type) => { setComposer(type); setCommand(false); }} />}
      {notifications && <NotificationPanel records={data.notifications} onClose={() => setNotifications(false)} update={update} />}
      {composer && <Composer type={composer} onClose={() => setComposer(null)} onSaved={() => { setComposer(null); router.refresh(); }} />}
    </div>
  );
}

function ConfigurationState({ error }: { error?: string }) {
  return <Empty icon={Database} title="Intelligence storage is not connected" body={error ?? "Set the server-side Supabase variables and apply the executive intelligence migration. No dashboard data is exposed publicly while storage is disconnected."} />;
}

function Overview({ data, metrics, update, working, setView, setComposer }: { data: DashboardData; metrics: { unreadBriefs: number; urgentActions: number; newOpportunities: number; activeRisks: number }; update: UpdateRecord; working: string | null; setView: (v: View) => void; setComposer: (v: "brief") => void }) {
  const latest = data.briefs[0];
  const actions = data.actions.filter((r) => !["completed","dismissed"].includes(str(r.status))).sort((a,b) => ({critical:4,high:3,medium:2,low:1}[str(b.priority) as "critical"] ?? 0) - ({critical:4,high:3,medium:2,low:1}[str(a.priority) as "critical"] ?? 0)).slice(0,5);
  const opportunity = data.opportunities[0];
  const risk = data.risks.find((r) => !["mitigated","closed"].includes(str(r.status)));
  const hour = new Date().getHours(); const greeting = hour < 12 ? "Good morning" : hour < 17 ? "Good afternoon" : "Good evening";
  return <div className="space-y-7">
    <section className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="font-mono text-[0.58rem] uppercase tracking-label text-crimson-light">{new Date().toLocaleDateString("en-US", { weekday: "long", month: "long", day: "numeric", year: "numeric" })}</p><h2 className="display mt-2 text-2xl sm:text-3xl">{greeting}, Joseph.</h2><p className="mt-2 text-white/48">Here is what requires your attention today.</p></div><button onClick={() => setComposer("brief")} className="btn-primary gap-2 self-start px-5 py-3"><FilePlus2 size={16} /> Add brief</button></section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Unread briefs" value={metrics.unreadBriefs} context="Awaiting executive review" icon={FileText} /><Metric label="Priority actions" value={metrics.urgentActions} context="Critical and high priority" icon={Zap} /><Metric label="New opportunities" value={metrics.newOpportunities} context="In discovered stage" icon={Target} /><Metric label="Active risks" value={metrics.activeRisks} context="Open or monitoring" icon={AlertTriangle} /></section>
    <section className="grid gap-5 xl:grid-cols-[1.4fr_0.8fr]">
      <div className="card p-6"><div className="flex items-center justify-between gap-3"><div><p className="font-mono text-[0.55rem] uppercase tracking-label text-white/35">Daily executive summary</p><h3 className="display mt-2 text-xl">{latest ? str(latest.title) : "No brief received today"}</h3></div>{latest && <Badge value={str(latest.priority,"medium")} />}</div>{latest ? <><p className="mt-4 max-w-3xl leading-7 text-white/62">{str(latest.executive_summary,"This brief does not include an executive summary.")}</p><div className="mt-5 flex items-center gap-3 text-xs text-white/35"><CalendarDays size={14} />{date(latest.brief_date)}<span>•</span><span>{str(latest.brief_type).replaceAll("_"," ")}</span></div><button onClick={() => setView("briefs")} className="mt-5 inline-flex items-center gap-1 text-sm text-crimson-light">Open full brief <ChevronRight size={15} /></button></> : <div className="mt-5"><p className="text-sm text-white/45">Connect an integration or add your first brief manually.</p><button onClick={() => setComposer("brief")} className="btn-ghost mt-4 px-5 py-2.5">Add first brief</button></div>}</div>
      <div className="space-y-4"><Signal title="Top opportunity" icon={TrendingUp} record={opportunity} text={opportunity ? str(opportunity.name) : "No opportunities identified."} meta={opportunity ? `Decision-support score ${num(opportunity.total_score)}/100` : "Not connected"} /><Signal title="Risk watch" icon={AlertTriangle} record={risk} text={risk ? str(risk.title) : "No active risks require attention."} meta={risk ? `${str(risk.severity)} severity` : "Clear"} /></div>
    </section>
    <section><div className="mb-4 flex items-end justify-between"><div><p className="font-mono text-[0.55rem] uppercase tracking-label text-white/35">Priority action queue</p><h3 className="display mt-2 text-xl">What to do next</h3></div><button onClick={() => setView("actions")} className="text-sm text-white/45 hover:text-white">View all</button></div>{actions.length ? <div className="card divide-y divide-white/[0.07]">{actions.map((item) => <div key={item.id} className="flex flex-col gap-4 p-4 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><Badge value={str(item.priority,"medium")} /><span className="font-mono text-[0.55rem] uppercase tracking-label text-white/30">Impact {num(item.impact_score) || "—"} / Effort {num(item.effort_score) || "—"}</span></div><h4 className="mt-2 font-medium text-white/90">{str(item.title)}</h4><p className="mt-1 truncate text-sm text-white/40">{str(item.why_it_matters, str(item.description,"No rationale supplied."))}</p></div><div className="flex gap-2"><button disabled={working === item.id} onClick={() => update("actions","actions",item.id,{ status:"planned", deferred_until:new Date(Date.now()+7*86400000).toISOString().slice(0,10) })} className="rounded-lg border border-white/10 px-3 py-2 text-xs text-white/50 hover:text-white">Defer 7d</button><button disabled={working === item.id} onClick={() => update("actions","actions",item.id,{ status:"completed", completed_at:new Date().toISOString() })} className="rounded-lg border border-emerald-400/20 bg-emerald-400/10 px-3 py-2 text-xs text-emerald-200"><Check size={14} className="inline" /> Complete</button></div></div>)}</div> : <Empty icon={CheckCircle2} title="No high-priority actions require attention" body="Approved action items from briefs will appear here." />}</section>
  </div>;
}

function Signal({ title, icon: Icon, record, text, meta }: { title: string; icon: Icon; record?: DashboardRecord; text: string; meta: string }) { return <div className="card p-5"><div className="flex items-center gap-2 font-mono text-[0.55rem] uppercase tracking-label text-white/35"><Icon size={14} className={record ? "text-crimson-light" : "text-white/30"} />{title}</div><p className="mt-3 font-medium text-white/82">{text}</p><p className="mt-2 text-xs capitalize text-white/35">{meta}</p></div>; }

function Briefs({ data, update, working, onCreate }: { data: DashboardData; update: UpdateRecord; working: string | null; onCreate: () => void }) {
  const [query, setQuery] = useState(""); const [priority, setPriority] = useState("all"); const [selected, setSelected] = useState(data.briefs[0]?.id ?? ""); const [compare, setCompare] = useState(false);
  const records = data.briefs.filter((r) => !bool(r.is_archived) && (priority === "all" || str(r.priority) === priority) && `${str(r.title)} ${str(r.executive_summary)} ${str(r.content_markdown)}`.toLowerCase().includes(query.toLowerCase()));
  const current = data.briefs.find((r) => r.id === selected) ?? records[0]; const previous = data.briefs.find((r) => r.id !== current?.id);
  return <div className="space-y-5"><Toolbar title="Daily brief archive" body={`${records.length} available brief${records.length === 1 ? "" : "s"}`} action={<button onClick={onCreate} className="btn-primary gap-2 px-5 py-3"><Plus size={16} /> Add brief</button>} />
    <div className="flex flex-wrap gap-3"><label className="relative min-w-56 flex-1"><span className="sr-only">Search briefs</span><Search size={15} className="absolute left-3 top-3 text-white/30" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search title, summary, or content" className="w-full rounded-lg border border-white/10 bg-white/[0.025] py-2.5 pl-9 pr-3 text-sm outline-none focus:border-crimson" /></label><select value={priority} onChange={(e) => setPriority(e.target.value)} aria-label="Filter by priority" className="rounded-lg border border-white/10 bg-base-800 px-3 py-2 text-sm text-white/60"><option value="all">All priorities</option><option>critical</option><option>high</option><option>medium</option><option>low</option></select>{data.briefs.length > 1 && <button onClick={() => setCompare(!compare)} className="rounded-lg border border-white/10 px-3 py-2 text-sm text-white/55">{compare ? "Close comparison" : "Compare latest"}</button>}</div>
    {compare && current && previous && <div className="card grid gap-4 p-5 md:grid-cols-2"><CompareColumn label="Current" brief={current} /><CompareColumn label="Previous" brief={previous} /><p className="md:col-span-2 text-xs text-white/35">Comparison shows explicit record differences only; it does not infer a semantic relationship.</p></div>}
    {records.length ? <div className="grid min-h-[650px] gap-5 lg:grid-cols-[320px_1fr]"><aside className="card h-fit divide-y divide-white/[0.06] overflow-hidden">{records.map((brief) => <button key={brief.id} onClick={() => { setSelected(brief.id); if (!bool(brief.is_read)) update("briefs","briefs",brief.id,{is_read:true}); }} className={`w-full p-4 text-left ${current?.id === brief.id ? "bg-crimson/[0.08]" : "hover:bg-white/[0.025]"}`}><div className="flex items-center gap-2"><span className={`h-2 w-2 rounded-full ${bool(brief.is_read) ? "bg-white/15" : "bg-crimson"}`} /><span className="font-mono text-[0.53rem] uppercase tracking-label text-white/35">{date(brief.brief_date)}</span>{bool(brief.is_pinned) && <Pin size={12} className="ml-auto text-crimson-light" />}</div><p className="mt-2 line-clamp-2 text-sm font-medium text-white/78">{str(brief.title)}</p><p className="mt-2 line-clamp-2 text-xs leading-5 text-white/35">{str(brief.executive_summary,"No summary")}</p></button>)}</aside>{current && <article className="card min-w-0 p-5 sm:p-7"><div className="flex flex-col justify-between gap-4 border-b border-white/10 pb-6 sm:flex-row"><div><div className="flex flex-wrap items-center gap-2"><Badge value={str(current.priority,"medium")} /><span className="font-mono text-[0.55rem] uppercase tracking-label text-white/35">{str(current.brief_type).replaceAll("_"," ")}</span></div><h2 className="display mt-4 text-2xl">{str(current.title)}</h2><p className="mt-2 text-sm text-white/40">Generated {date(current.generated_at ?? current.brief_date)} · {str(current.schedule_name,"Manual brief")}</p></div><div className="flex gap-2"><button disabled={working===current.id} onClick={() => update("briefs","briefs",current.id,{is_pinned:!bool(current.is_pinned)})} className="rounded-lg border border-white/10 p-2.5 text-white/50" aria-label={bool(current.is_pinned)?"Unpin brief":"Pin brief"}><Pin size={16} /></button><button disabled={working===current.id} onClick={() => update("briefs","briefs",current.id,{is_archived:true,status:"archived"})} className="rounded-lg border border-white/10 p-2.5 text-white/50" aria-label="Archive brief"><Archive size={16} /></button></div></div><div className="my-6 rounded-lg border border-crimson/15 bg-crimson/[0.05] p-5"><p className="font-mono text-[0.55rem] uppercase tracking-label text-crimson-light">Executive summary</p><p className="mt-3 leading-7 text-white/70">{str(current.executive_summary,"No executive summary was supplied.")}</p></div><MarkdownRenderer content={str(current.content_markdown,"No full report content was supplied.")} /></article>}</div> : <Empty icon={FileText} title="No daily briefs have been received yet" body="Connect an integration or add your first brief manually." action={<button onClick={onCreate} className="btn-primary px-5 py-3">Add first brief</button>} />}
  </div>;
}

function CompareColumn({ label, brief }: { label: string; brief: DashboardRecord }) { return <div><p className="font-mono text-[0.55rem] uppercase tracking-label text-crimson-light">{label} · {date(brief.brief_date)}</p><h3 className="mt-2 font-medium">{str(brief.title)}</h3><p className="mt-2 line-clamp-4 text-sm leading-6 text-white/45">{str(brief.executive_summary,"No summary")}</p></div>; }
function Toolbar({ title, body, action }: { title: string; body: string; action?: React.ReactNode }) { return <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h2 className="display text-2xl">{title}</h2><p className="mt-2 text-sm text-white/42">{body}</p></div>{action}</div>; }

function Actions({ records, update, working, onCreate }: { records: DashboardRecord[]; update: UpdateRecord; working: string | null; onCreate: () => void }) {
  const [mode,setMode]=useState<"kanban"|"list"|"calendar">("kanban"); const active=records.filter(r=>!['dismissed'].includes(str(r.status)));
  return <div className="space-y-5"><Toolbar title="Action center" body="Turn intelligence into reviewed, owned work." action={<button onClick={onCreate} className="btn-primary gap-2 px-5 py-3"><Plus size={16}/> Create task</button>} /><div className="flex gap-2">{(["kanban","list","calendar"] as const).map(v=><button key={v} onClick={()=>setMode(v)} className={`rounded-lg border px-3 py-2 text-xs capitalize ${mode===v?'border-crimson/40 bg-crimson/10 text-white':'border-white/10 text-white/45'}`}>{v}</button>)}</div>{active.length===0?<Empty icon={CheckCircle2} title="No actions require attention" body="Actions extracted from briefs remain in review until an administrator approves them."/>:mode==='kanban'?<div className="grid gap-4 xl:grid-cols-4">{["new","reviewing","in_progress","completed"].map(status=><div key={status} className="space-y-3"><div className="flex items-center justify-between"><h3 className="font-mono text-[0.58rem] uppercase tracking-label text-white/45">{status.replaceAll('_',' ')}</h3><span className="text-xs text-white/25">{active.filter(r=>str(r.status)===status).length}</span></div>{active.filter(r=>str(r.status)===status).map(r=><ActionCard key={r.id} item={r} update={update} working={working}/>)}</div>)}</div>:mode==='calendar'?<div className="card divide-y divide-white/[0.06]">{active.filter(r=>r.due_date).sort((a,b)=>str(a.due_date).localeCompare(str(b.due_date))).map(r=><div key={r.id} className="flex items-center gap-4 p-4"><CalendarDays size={16} className="text-crimson-light"/><span className="w-28 font-mono text-xs text-white/45">{date(r.due_date)}</span><span className="flex-1 text-sm">{str(r.title)}</span><Badge value={str(r.priority,"medium")}/></div>)}{!active.some(r=>r.due_date)&&<div className="p-8 text-center text-sm text-white/40">No task due dates are set.</div>}</div>:<div className="card divide-y divide-white/[0.06]">{active.map(r=><div key={r.id} className="p-4"><ActionCard item={r} update={update} working={working}/></div>)}</div>}</div>;
}
function ActionCard({item,update,working}:{item:DashboardRecord;update:UpdateRecord;working:string|null}) { return <div className="card p-4"><div className="flex items-center justify-between gap-2"><Badge value={str(item.priority,"medium")}/>{bool(item.requires_review)&&<span className="text-[0.6rem] text-amber-200">Review required</span>}</div><h4 className="mt-3 text-sm font-medium text-white/85">{str(item.title)}</h4><p className="mt-2 line-clamp-3 text-xs leading-5 text-white/38">{str(item.description,"No description")}</p><div className="mt-4 flex items-center justify-between text-[0.65rem] text-white/30"><span>{date(item.due_date)}</span><span>{relatedTitle(item)}</span></div><select disabled={working===item.id} value={str(item.status,"new")} onChange={e=>update("actions","actions",item.id,{status:e.target.value,...(e.target.value==='completed'?{completed_at:new Date().toISOString()}:{}),...(bool(item.requires_review)?{requires_review:false,approved_at:new Date().toISOString()}: {})})} aria-label={`Status for ${str(item.title)}`} className="mt-4 w-full rounded-lg border border-white/10 bg-base-800 px-3 py-2 text-xs text-white/60"><option value="new">New</option><option value="reviewing">Reviewing</option><option value="planned">Planned</option><option value="in_progress">In progress</option><option value="blocked">Blocked</option><option value="completed">Completed</option><option value="dismissed">Dismissed</option></select></div>; }

function Opportunities({records,update,working,onCreate}:{records:DashboardRecord[];update:UpdateRecord;working:string|null;onCreate:()=>void}) { const horizons=["immediate","near_term","long_term","experimental"]; return <div className="space-y-5"><Toolbar title="Opportunity radar" body="Decision-support scores are transparent aids, not objective facts." action={<button onClick={onCreate} className="btn-primary gap-2 px-5 py-3"><Plus size={16}/> Add opportunity</button>}/>{records.length?<div className="grid gap-5 xl:grid-cols-4">{horizons.map(h=><section key={h}><h3 className="mb-3 font-mono text-[0.58rem] uppercase tracking-label text-white/45">{h.replaceAll('_',' ')}</h3><div className="space-y-3">{records.filter(r=>str(r.horizon,"near_term")===h).map(r=><div key={r.id} className="card p-4"><div className="flex items-start justify-between gap-3"><Badge value={str(r.stage,"discovered")}/><span className="font-mono text-lg text-white">{num(r.total_score)}<small className="text-[0.55rem] text-white/30">/100</small></span></div><h4 className="mt-3 font-medium">{str(r.name)}</h4><p className="mt-2 line-clamp-3 text-xs leading-5 text-white/40">{str(r.description,"No description")}</p><p className="mt-3 text-xs text-crimson-light">{str(r.recommended_next_step,"No next step recorded")}</p><select disabled={working===r.id} value={str(r.stage,"discovered")} onChange={e=>update("opportunities","opportunities",r.id,{stage:e.target.value,...(bool(r.requires_review)?{requires_review:false,approved_at:new Date().toISOString()}: {})})} className="mt-4 w-full rounded-lg border border-white/10 bg-base-800 px-3 py-2 text-xs text-white/60" aria-label={`Stage for ${str(r.name)}`}><option>discovered</option><option>reviewing</option><option>validating</option><option>approved</option><option>building</option><option>launched</option><option>paused</option><option>rejected</option></select></div>)}</div></section>)}</div>:<Empty icon={Target} title="No opportunities match the selected filters" body="Opportunities extracted from briefs or created manually will appear here." action={<button onClick={onCreate} className="btn-primary px-5 py-3">Add opportunity</button>}/>}</div>; }

function Intelligence({records}:{records:DashboardRecord[]}) { const [q,setQ]=useState(""); const [category,setCategory]=useState("all"); const cats=Array.from(new Set(records.map(r=>str(r.category)).filter(Boolean))); const filtered=records.filter(r=>(category==='all'||str(r.category)===category)&&`${str(r.headline)} ${str(r.summary)} ${str(r.why_it_matters)}`.toLowerCase().includes(q.toLowerCase())); return <div className="space-y-5"><Toolbar title="Intelligence library" body="Publication, event, and observation dates remain distinct."/><div className="flex gap-3"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search intelligence" className="min-w-0 flex-1 rounded-lg border border-white/10 bg-white/[0.025] px-3 py-2.5 text-sm outline-none"/><select value={category} onChange={e=>setCategory(e.target.value)} className="rounded-lg border border-white/10 bg-base-800 px-3 text-sm text-white/55"><option value="all">All categories</option>{cats.map(c=><option key={c}>{c}</option>)}</select></div>{filtered.length?<div className="card divide-y divide-white/[0.06]">{filtered.map(r=><article key={r.id} className="p-5"><div className="flex flex-wrap items-center gap-2"><Badge value={str(r.urgency,"medium")}/><span className="font-mono text-[0.55rem] uppercase tracking-label text-white/30">{str(r.category,"other")}</span><span className="ml-auto text-xs text-white/30">Observed {date(r.date_observed)}</span></div><h3 className="mt-3 font-medium text-white/88">{str(r.headline)}</h3><p className="mt-2 text-sm leading-6 text-white/48">{str(r.summary,"No summary")}</p>{Boolean(r.why_it_matters)&&<p className="mt-3 border-l-2 border-crimson/40 pl-3 text-sm text-white/60"><span className="text-crimson-light">Why it matters: </span>{str(r.why_it_matters)}</p>}<div className="mt-4 flex flex-wrap gap-4 font-mono text-[0.55rem] uppercase tracking-label text-white/25"><span>Event {date(r.event_date)}</span><span>Published {date(r.publication_date)}</span><span>Confidence {num(r.confidence)||'—'}%</span></div></article>)}</div>:<Empty icon={Radar} title="No intelligence items found" body="Items extracted from processed briefs will appear here."/>}</div>; }

function Risks({records,update,working,onCreate}:{records:DashboardRecord[];update:UpdateRecord;working:string|null;onCreate:()=>void}) { return <div className="space-y-5"><Toolbar title="Risks and watchlist" body="Monitor threats, probability, impact, and mitigation." action={<button onClick={onCreate} className="btn-primary gap-2 px-5 py-3"><Plus size={16}/> Add risk</button>}/>{records.length?<div className="grid gap-4 lg:grid-cols-2">{records.map(r=><article key={r.id} className="card p-5"><div className="flex items-center justify-between"><Badge value={str(r.severity,"medium")}/><span className="font-mono text-xs text-white/35">{num(r.probability)||'—'}% probability</span></div><h3 className="mt-4 font-medium">{str(r.title)}</h3><p className="mt-2 text-sm leading-6 text-white/45">{str(r.description,"No description")}</p><div className="mt-4 rounded-lg bg-white/[0.025] p-3 text-xs leading-5 text-white/50"><span className="text-crimson-light">Mitigation: </span>{str(r.mitigation,"Not defined")}</div><select disabled={working===r.id} value={str(r.status,"monitoring")} onChange={e=>update("risks","risks",r.id,{status:e.target.value,last_reviewed_at:new Date().toISOString()})} className="mt-4 rounded-lg border border-white/10 bg-base-800 px-3 py-2 text-xs text-white/60"><option>active</option><option>monitoring</option><option>mitigated</option><option>accepted</option><option>closed</option></select></article>)}</div>:<Empty icon={ShieldCheck} title="No active risks require attention" body="Risks identified in briefs will be tracked here." action={<button onClick={onCreate} className="btn-primary px-5 py-3">Add risk</button>}/>}</div>; }

function Ideas({records,update,onCreate}:{records:DashboardRecord[];update:UpdateRecord;onCreate:()=>void}) { return <div className="space-y-5"><Toolbar title="Ideas portfolio" body="Service, product, content, and operational concepts worth exploring." action={<button onClick={onCreate} className="btn-primary gap-2 px-5 py-3"><Plus size={16}/> Capture idea</button>}/>{records.length?<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{records.map(r=><article key={r.id} className="card p-5"><div className="flex items-center justify-between"><Lightbulb size={17} className="text-crimson-light"/><Badge value={str(r.status,"captured")}/></div><h3 className="mt-4 font-medium">{str(r.title)}</h3><p className="mt-2 text-sm leading-6 text-white/42">{str(r.description,"No description")}</p><p className="mt-4 text-xs text-crimson-light">{str(r.next_step,"No next step recorded")}</p><select value={str(r.status,"captured")} onChange={e=>update("ideas","ideas",r.id,{status:e.target.value})} className="mt-4 w-full rounded-lg border border-white/10 bg-base-800 px-3 py-2 text-xs text-white/60"><option>captured</option><option>reviewing</option><option>validated</option><option>building</option><option>shipped</option><option>dismissed</option></select></article>)}</div>:<Empty icon={Sparkles} title="No ideas have been captured" body="Add an idea manually or ingest briefs containing product and service concepts." action={<button onClick={onCreate} className="btn-primary px-5 py-3">Capture idea</button>}/>}</div>; }

function Analytics({data}:{data:DashboardData}) { const bars=[['Briefs',data.briefs.length],['Opportunities',data.opportunities.length],['Actions',data.actions.length],['Intelligence',data.intelligence.length],['Risks',data.risks.length]] as const; const max=Math.max(1,...bars.map(([,v])=>v)); const completed=data.actions.filter(r=>str(r.status)==='completed').length; return <div className="space-y-6"><Toolbar title="Executive analytics" body="Every visualization is calculated from connected dashboard records."/><div className="grid gap-4 sm:grid-cols-3"><Metric label="Brief coverage" value={data.briefs.length} context="Briefs loaded in the current 100-record window" icon={FileText}/><Metric label="Action completion" value={data.actions.length?`${Math.round(completed/data.actions.length*100)}%`:'—'} context={`${completed} of ${data.actions.length} actions completed`} icon={CheckCircle2}/><Metric label="Open opportunity value" value={data.opportunities.length} context="Structured opportunities under review" icon={Target}/></div>{bars.some(([,v])=>v>0)?<div className="card p-6"><h3 className="display text-lg">Intelligence pipeline composition</h3><p className="mt-1 text-xs text-white/35">How many structured records each brief workflow has produced.</p><div className="mt-7 space-y-5">{bars.map(([label,value])=><div key={label}><div className="mb-2 flex justify-between text-xs"><span className="text-white/55">{label}</span><span className="font-mono text-white/40">{value} records</span></div><div className="h-2 rounded-full bg-white/[0.05]"><div className="h-full rounded-full bg-crimson" style={{width:`${value/max*100}%`}}/></div></div>)}</div></div>:<Empty icon={BarChart3} title="Analytics will appear after briefs have been processed" body="No vanity metrics are displayed. Charts populate only from connected records."/>}</div>; }

function Sources({records}:{records:DashboardRecord[]}) { return <div className="space-y-5"><Toolbar title="Source register" body="Trace every publication, company, report, and reference used in briefs."/>{records.length?<div className="card overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b border-white/10 font-mono text-[0.55rem] uppercase tracking-label text-white/35"><th className="p-4 font-normal">Source</th><th className="p-4 font-normal">Publisher</th><th className="p-4 font-normal">Type</th><th className="p-4 font-normal">Credibility</th><th className="p-4 font-normal">Published</th></tr></thead><tbody>{records.map(r=><tr key={r.id} className="border-b border-white/[0.06]"><td className="p-4">{r.url?<a href={str(r.url)} target="_blank" rel="noopener noreferrer" className="text-white/80 hover:text-crimson-light">{str(r.title)}</a>:str(r.title)}</td><td className="p-4 text-white/45">{str(r.publisher,"—")}</td><td className="p-4 text-white/45">{str(r.source_type,"other").replaceAll('_',' ')}</td><td className="p-4"><Badge value={str(r.credibility_level,"unclassified")}/></td><td className="p-4 text-white/40">{date(r.publication_date)}</td></tr>)}</tbody></table></div></div>:<Empty icon={BookOpen} title="No sources have been recorded" body="Source links from incoming briefs will remain traceable here."/>}</div>; }

function SettingsPanel({data}:{data:DashboardData}) { const defaults=[{name:'Secure webhook',type:'webhook',need:'BRIEF_INGESTION_SECRET'},{name:'Gmail brief inbox',type:'gmail',need:'Google OAuth client, refresh token, allowed senders'},{name:'Google Calendar context',type:'google_calendar',need:'Google OAuth client, refresh token, calendar ID'}]; return <div className="space-y-6"><Toolbar title="Settings and integrations" body="Connections remain disabled until their own production credentials are configured."/><section><h3 className="display mb-4 text-lg">Brief integrations</h3><div className="grid gap-4 lg:grid-cols-3">{defaults.map(item=>{const connected=data.integrations.find(r=>str(r.integration_type)===item.type);return <div key={item.type} className="card p-5"><div className="flex items-center justify-between"><Database size={17} className="text-crimson-light"/><Badge value={connected?str(connected.status,'disconnected'):'disconnected'}/></div><h4 className="mt-4 font-medium">{item.name}</h4><p className="mt-2 text-xs leading-5 text-white/40">Required: {item.need}</p><p className="mt-4 font-mono text-[0.55rem] uppercase tracking-label text-white/25">Last success {connected?date(connected.last_success_at):'Never'}</p></div>})}</div></section><section className="card p-6"><h3 className="display text-lg">AI processing</h3><p className="mt-2 text-sm text-white/45">Provider abstraction and review-state storage are ready. AI extraction remains disabled until a provider key and processing workflow are configured. Generated records require review by default.</p><div className="mt-4 inline-flex items-center gap-2 rounded-full border border-white/10 px-3 py-1.5 text-xs text-white/40"><CircleDot size={13}/> Disabled · review required</div></section><section className="card overflow-hidden"><div className="border-b border-white/10 p-5"><h3 className="display text-lg">Ingestion log</h3></div>{data.ingestionLogs.length?<div className="divide-y divide-white/[0.06]">{data.ingestionLogs.slice(0,10).map(r=><div key={r.id} className="flex flex-wrap items-center gap-3 p-4 text-xs"><Badge value={str(r.status)}/><span className="font-mono text-white/35">{date(r.received_at)}</span><span className="truncate text-white/35">{str(r.idempotency_key)}</span>{Boolean(r.error_message)&&<span className="ml-auto text-crimson-light">{str(r.error_message)}</span>}</div>)}</div>:<p className="p-6 text-sm text-white/40">No ingestion attempts have been logged.</p>}</section></div>; }

function CommandPalette({data,onClose,onView,onCreate}:{data:DashboardData;onClose:()=>void;onView:(v:View)=>void;onCreate:(v:"actions"|"opportunities"|"brief")=>void}) { const [q,setQ]=useState(''); const results=useMemo(()=>[...data.briefs.map(r=>({label:str(r.title),view:'briefs' as View,type:'Brief'})),...data.actions.map(r=>({label:str(r.title),view:'actions' as View,type:'Action'})),...data.opportunities.map(r=>({label:str(r.name),view:'opportunities' as View,type:'Opportunity'})),...data.risks.map(r=>({label:str(r.title),view:'risks' as View,type:'Risk'})),...data.intelligence.map(r=>({label:str(r.headline),view:'intelligence' as View,type:'Intelligence'})),...data.ideas.map(r=>({label:str(r.title),view:'ideas' as View,type:'Idea'})),...data.sources.map(r=>({label:str(r.title),view:'sources' as View,type:'Source'}))].filter(r=>r.label.toLowerCase().includes(q.toLowerCase())).slice(0,10),[data,q]); return <Modal onClose={onClose}><div className="border-b border-white/10 p-4"><label className="flex items-center gap-3"><Search size={18} className="text-white/35"/><span className="sr-only">Search dashboard</span><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Search briefs, actions, opportunities, risks…" className="min-w-0 flex-1 bg-transparent py-2 text-sm outline-none"/></label></div><div className="max-h-[60vh] overflow-y-auto p-2">{!q&&<><PaletteButton label="Open latest brief" icon={FileText} onClick={()=>onView('briefs')}/><PaletteButton label="Create task" icon={ListChecks} onClick={()=>onCreate('actions')}/><PaletteButton label="Create opportunity" icon={Target} onClick={()=>onCreate('opportunities')}/><PaletteButton label="View critical risks" icon={AlertTriangle} onClick={()=>onView('risks')}/><PaletteButton label="Open settings" icon={Settings} onClick={()=>onView('settings')}/></>}{q&&results.map((r,i)=><button key={`${r.type}-${i}`} onClick={()=>onView(r.view)} className="flex w-full items-center gap-3 rounded-lg px-3 py-3 text-left hover:bg-white/[0.04]"><span className="rounded bg-white/[0.05] px-2 py-1 font-mono text-[0.52rem] uppercase text-white/35">{r.type}</span><span className="truncate text-sm text-white/70">{r.label}</span></button>)}{q&&!results.length&&<p className="p-6 text-center text-sm text-white/35">No dashboard records match this search.</p>}</div></Modal>; }
function PaletteButton({label,icon:Icon,onClick}:{label:string;icon:Icon;onClick:()=>void}) { return <button onClick={onClick} className="flex w-full items-center gap-3 rounded-lg px-3 py-3 text-left text-sm text-white/60 hover:bg-white/[0.04] hover:text-white"><Icon size={16} className="text-crimson-light"/>{label}<ChevronRight size={14} className="ml-auto text-white/20"/></button>; }

function NotificationPanel({records,onClose,update}:{records:DashboardRecord[];onClose:()=>void;update:UpdateRecord}) { return <div className="fixed inset-0 z-[80] flex justify-end bg-black/65" onMouseDown={e=>{if(e.currentTarget===e.target)onClose()}}><aside className="h-full w-full max-w-md overflow-y-auto border-l border-white/10 bg-base-900 p-5"><div className="flex items-center justify-between"><h2 className="display text-xl">Notifications</h2><button onClick={onClose} className="p-2 text-white/50" aria-label="Close"><X size={18}/></button></div><div className="mt-5 space-y-3">{records.length?records.map(r=><button key={r.id} onClick={()=>!bool(r.is_read)&&update("notifications","notifications",r.id,{is_read:true})} className={`card w-full p-4 text-left ${bool(r.is_read)?'opacity-55':'border-crimson/25'}`}><div className="flex items-center gap-2"><Bell size={14} className="text-crimson-light"/><span className="font-medium text-sm">{str(r.title)}</span></div><p className="mt-2 text-xs leading-5 text-white/40">{str(r.message)}</p><p className="mt-2 font-mono text-[0.52rem] uppercase tracking-label text-white/25">{date(r.created_at)}</p></button>):<Empty icon={Bell} title="No notifications" body="System and intelligence alerts will appear here."/>}</div></aside></div>; }

function Modal({children,onClose}:{children:React.ReactNode;onClose:()=>void}) { return <div className="fixed inset-0 z-[90] flex items-start justify-center bg-black/75 p-4 pt-[12vh]" role="dialog" aria-modal="true" onMouseDown={e=>{if(e.currentTarget===e.target)onClose()}}><div className="w-full max-w-2xl overflow-hidden rounded-xl border border-white/12 bg-base-900 shadow-lift">{children}</div></div>; }

function Composer({type,onClose,onSaved}:{type:"brief"|"actions"|"opportunities"|"risks"|"ideas";onClose:()=>void;onSaved:()=>void}) { const [saving,setSaving]=useState(false); const [preview,setPreview]=useState(false); const [error,setError]=useState(''); const [form,setForm]=useState({title:'',summary:'',content:'',priority:'medium',date:new Date().toISOString().slice(0,10),description:'',nextStep:''}); const label=type==='brief'?'brief':type.slice(0,-1); async function submit(e:FormEvent){e.preventDefault();setSaving(true);setError(''); let response:Response; if(type==='brief') response=await postJson('/api/dashboard/briefs',{title:form.title,briefType:'manual',briefDate:form.date,executiveSummary:form.summary,contentMarkdown:form.content,priority:form.priority,sections:[],actions:[],opportunities:[],risks:[],intelligence:[],sources:[],tags:[]}); else { const body=type==='actions'?{title:form.title,description:form.description,priority:form.priority,status:'new',requires_review:false}:type==='opportunities'?{name:form.title,description:form.description,opportunity_type:'operational_improvement',stage:'discovered',horizon:'near_term',recommended_next_step:form.nextStep,requires_review:false}:type==='risks'?{title:form.title,description:form.description,severity:form.priority,status:'monitoring',mitigation:form.nextStep}:{title:form.title,description:form.description,idea_type:'service',status:'captured',next_step:form.nextStep}; response=await postJson(`/api/dashboard/entities/${type}`,body);} const payload=await response.json().catch(()=>({})); setSaving(false); if(!response.ok){setError(payload.error??'Could not save.');return;} onSaved(); }
  return <Modal onClose={onClose}><form onSubmit={submit}><div className="flex items-center justify-between border-b border-white/10 p-5"><div><p className="font-mono text-[0.53rem] uppercase tracking-label text-crimson-light">Manual entry</p><h2 className="display mt-1 text-xl">Create {label}</h2></div><button type="button" onClick={onClose} className="p-2 text-white/50"><X size={18}/></button></div><div className="max-h-[65vh] space-y-4 overflow-y-auto p-5"><Field label="Title" value={form.title} onChange={v=>setForm({...form,title:v})} required/>{type==='brief'?<><div className="grid gap-4 sm:grid-cols-2"><Field label="Brief date" type="date" value={form.date} onChange={v=>setForm({...form,date:v})} required/><SelectField label="Priority" value={form.priority} onChange={v=>setForm({...form,priority:v})}/></div><Area label="Executive summary" value={form.summary} onChange={v=>setForm({...form,summary:v})}/><Area label="Full report (Markdown)" value={form.content} onChange={v=>setForm({...form,content:v})} rows={8}/>{preview&&<div className="rounded-lg border border-white/10 bg-white/[0.02] p-4"><MarkdownRenderer content={form.content||'Nothing to preview yet.'}/></div>}</>:<><Area label="Description" value={form.description} onChange={v=>setForm({...form,description:v})}/>{type!=='ideas'&&<SelectField label={type==='risks'?'Severity':'Priority'} value={form.priority} onChange={v=>setForm({...form,priority:v})}/>} {type!=='actions'&&<Area label={type==='risks'?'Mitigation':'Recommended next step'} value={form.nextStep} onChange={v=>setForm({...form,nextStep:v})}/>}</>}{error&&<p role="alert" className="text-sm text-crimson-light">{error}</p>}</div><div className="flex items-center justify-end gap-3 border-t border-white/10 p-5">{type==='brief'&&<button type="button" onClick={()=>setPreview(!preview)} className="mr-auto text-sm text-white/45">{preview?'Hide preview':'Preview'}</button>}<button type="button" onClick={onClose} className="rounded-lg border border-white/10 px-4 py-2 text-sm text-white/55">Cancel</button><button disabled={saving} className="btn-primary px-5 py-2.5">{saving?'Saving…':'Save'}</button></div></form></Modal>; }
function Field({label,value,onChange,type='text',required=false}:{label:string;value:string;onChange:(v:string)=>void;type?:string;required?:boolean}) { return <label className="block"><span className="mb-1.5 block font-mono text-[0.55rem] uppercase tracking-label text-white/40">{label}</span><input type={type} required={required} value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-lg border border-white/10 bg-white/[0.025] px-3 py-2.5 text-sm outline-none focus:border-crimson"/></label>; }
function Area({label,value,onChange,rows=4}:{label:string;value:string;onChange:(v:string)=>void;rows?:number}) { return <label className="block"><span className="mb-1.5 block font-mono text-[0.55rem] uppercase tracking-label text-white/40">{label}</span><textarea rows={rows} value={value} onChange={e=>onChange(e.target.value)} className="w-full resize-y rounded-lg border border-white/10 bg-white/[0.025] px-3 py-2.5 text-sm leading-6 outline-none focus:border-crimson"/></label>; }
function SelectField({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}) { return <label className="block"><span className="mb-1.5 block font-mono text-[0.55rem] uppercase tracking-label text-white/40">{label}</span><select value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-lg border border-white/10 bg-base-800 px-3 py-2.5 text-sm"><option>critical</option><option>high</option><option>medium</option><option>low</option></select></label>; }
