// ============ THE FORGE — firmware generator (ESP32-S3 Arduino) ============
export function generateFirmware(spec) {
  const e = spec.derived.elec;
  const m = spec.modules;
  const rows = e.matrix.rows, cols = e.matrix.cols;
  const keymapRows = buildKeymap(spec);
  const profiles = spec.profiles.map(p => p.toUpperCase());

  return `// ============================================================
// ${spec.name} — firmware rev ${spec.rev}
// Generated by THE FORGE for ESP32-S3 (Arduino core >= 3.0)
//
// Board:   ESP32-S3-DevKitC-1  (Tools > USB Mode: "USB-OTG (TinyUSB)")
// Needs:   Adafruit_SSD1306 (if OLED), Wire
// Flash:   arduino-cli compile --fqbn esp32:esp32:esp32s3 .
// ============================================================
#include <Arduino.h>
#include "USB.h"
#include "USBHIDKeyboard.h"
#include "USBHIDMouse.h"
#include "USBHIDConsumerControl.h"
#include <Wire.h>
${m.oled.present ? '#include <Adafruit_GFX.h>\n#include <Adafruit_SSD1306.h>' : ""}

USBHIDKeyboard        Kbd;
USBHIDMouse           Mouse;
USBHIDConsumerControl Consumer;

// ---------------- matrix ----------------
#define N_ROWS ${rows.length}
#define N_COLS ${cols.length}
const uint8_t ROW_PINS[N_ROWS] = { ${rows.join(", ")} };
const uint8_t COL_PINS[N_COLS] = { ${cols.join(", ")} };
bool keyState[N_ROWS][N_COLS] = {};
uint32_t keyT[N_ROWS][N_COLS] = {};
#define DEBOUNCE_MS 6

// ---------------- profiles ----------------
enum Profile { ${profiles.join(", ")} };
Profile profile = ${profiles[1] || profiles[0]};
const char* PROFILE_NAMES[] = { ${profiles.map(p => `"${p}"`).join(", ")} };
#define N_PROFILES ${profiles.length}

// Keymap [profile][row][col] — 0 = unassigned. Edit freely.
// KC() wraps plain HID usage; MACRO_n slots dispatch to runMacro().
#define MACRO_BASE 0xF0
const uint16_t KEYMAP[N_PROFILES][N_ROWS][N_COLS] = {
${keymapRows}};

${e.encoders.length ? `// ---------------- encoders ----------------
#define N_ENC ${e.encoders.length}
const uint8_t ENC_A[N_ENC]  = { ${e.encoders.map(x => x.a).join(", ")} };
const uint8_t ENC_B[N_ENC]  = { ${e.encoders.map(x => x.b).join(", ")} };
const uint8_t ENC_SW[N_ENC] = { ${e.encoders.map(x => x.sw).join(", ")} };
volatile int8_t encDelta[N_ENC] = {};
int8_t encLast[N_ENC];

void IRAM_ATTR encISR() {
  for (int i = 0; i < N_ENC; i++) {
    int8_t a = digitalRead(ENC_A[i]), b = digitalRead(ENC_B[i]);
    int8_t s = (a << 1) | b;
    if (s != encLast[i]) {
      if (((encLast[i] == 0b00) && (s == 0b01)) || ((encLast[i] == 0b11) && (s == 0b10))) encDelta[i]++;
      if (((encLast[i] == 0b00) && (s == 0b10)) || ((encLast[i] == 0b11) && (s == 0b01))) encDelta[i]--;
      encLast[i] = s;
    }
  }
}` : ""}

${m.pedals.count ? `// ---------------- foot pedals ----------------
#define N_PEDALS ${m.pedals.count}
const uint8_t PEDAL_PINS[N_PEDALS] = { ${e.pedals.map(p => p.pin).join(", ")} };
bool pedalState[N_PEDALS] = {};
// Pedal actions per profile: {gaming, coding, editing, business}
const uint16_t PEDAL_MAP[N_PROFILES][N_PEDALS] = {
${spec.profiles.map(() => `  { ${Array.from({ length: m.pedals.count }, (_, i) => ["HID_KEY_CONTROL_LEFT", "HID_KEY_SHIFT_LEFT", "MACRO_BASE+8", "HID_KEY_SPACE"][i]).join(", ")} },`).join("\n")}
};` : ""}

${m.oled.present ? `// ---------------- OLED ----------------
Adafruit_SSD1306 oled(128, 64, &Wire, -1);
uint32_t oledDirty = 1;
void drawStatus() {
  oled.clearDisplay();
  oled.setTextColor(SSD1306_WHITE);
  oled.setTextSize(2);
  oled.setCursor(0, 0);  oled.print("${spec.name.split(" ")[0].toUpperCase()}");
  oled.setTextSize(1);
  oled.setCursor(0, 22); oled.print("Profile: "); oled.print(PROFILE_NAMES[profile]);
  oled.setCursor(0, 34); oled.print("Host: PC"); oled.print(activePC + 1);
  oled.setCursor(0, 50); oled.print("rev ${spec.rev} | THE FORGE");
  oled.display();
}` : ""}

${m.trackball.present ? `// ---------------- I2C trackball (Pimoroni PIM447) ----------------
#define TB_ADDR 0x0A
#define TB_SPEED 3
void pollTrackball() {
  Wire.beginTransmission(TB_ADDR);
  Wire.write(0x04);                       // LEFT/RIGHT/UP/DOWN/SWITCH regs
  if (Wire.endTransmission(false) != 0) return;
  Wire.requestFrom(TB_ADDR, 5);
  if (Wire.available() < 5) return;
  int8_t left = Wire.read(), right = Wire.read(), up = Wire.read(), down = Wire.read();
  uint8_t sw = Wire.read();
  int dx = (right - left) * TB_SPEED, dy = (down - up) * TB_SPEED;
  if (dx || dy) Mouse.move(dx, dy);
  static bool swWas = false;
  bool swNow = sw & 0x80;
  if (swNow != swWas) { swNow ? Mouse.press(MOUSE_LEFT) : Mouse.release(MOUSE_LEFT); swWas = swNow; }
}` : ""}

// ---------------- host / KVM switching ----------------
uint8_t activePC = 0;
void switchPC(uint8_t pc) {
  activePC = pc;
  // PiKVM / DDC hotkey convention: ScrollLock ScrollLock <n>
  Kbd.press(HID_KEY_SCROLL_LOCK); Kbd.releaseAll(); delay(60);
  Kbd.press(HID_KEY_SCROLL_LOCK); Kbd.releaseAll(); delay(60);
  Kbd.press(HID_KEY_1 + pc);      Kbd.releaseAll();
${m.oled.present ? "  oledDirty = 1;" : ""}
}

// ---------------- macros ----------------
void runMacro(uint8_t n) {
  switch (n) {
    case 0: switchPC(0); break;                       // PC1
    case 1: switchPC(1); break;                       // PC2
    case 2: switchPC(2); break;                       // PC3
    case 3: /* PiKVM web OSD */ Kbd.press(HID_KEY_GUI_LEFT); Kbd.press(HID_KEY_F12); Kbd.releaseAll(); break;
    case 4: /* voice input  */ Kbd.press(HID_KEY_GUI_LEFT); Kbd.press(HID_KEY_H); Kbd.releaseAll(); break;
    case 5: profile = (Profile)((profile + 1) % N_PROFILES); ${m.oled.present ? "oledDirty = 1;" : ""} break;
    case 6: Consumer.press(CONSUMER_CONTROL_PLAY_PAUSE); Consumer.release(); break;
    case 7: Consumer.press(CONSUMER_CONTROL_MUTE); Consumer.release(); break;
    case 8: Kbd.press(HID_KEY_CONTROL_LEFT); Kbd.press(HID_KEY_Z); Kbd.releaseAll(); break;
    default: break;
  }
}

void tapCode(uint16_t code, bool down) {
  if (code == 0) return;
  if (code >= MACRO_BASE) { if (down) runMacro(code - MACRO_BASE); return; }
  down ? Kbd.pressRaw(code) : Kbd.releaseRaw(code);
}

// ---------------- setup / loop ----------------
void setup() {
  for (int r = 0; r < N_ROWS; r++) { pinMode(ROW_PINS[r], INPUT_PULLUP); }
  for (int c = 0; c < N_COLS; c++) { pinMode(COL_PINS[c], OUTPUT); digitalWrite(COL_PINS[c], HIGH); }
${e.encoders.length ? `  for (int i = 0; i < N_ENC; i++) {
    pinMode(ENC_A[i], INPUT_PULLUP); pinMode(ENC_B[i], INPUT_PULLUP); pinMode(ENC_SW[i], INPUT_PULLUP);
    encLast[i] = (digitalRead(ENC_A[i]) << 1) | digitalRead(ENC_B[i]);
    attachInterrupt(ENC_A[i], encISR, CHANGE); attachInterrupt(ENC_B[i], encISR, CHANGE);
  }` : ""}
${m.pedals.count ? `  for (int i = 0; i < N_PEDALS; i++) pinMode(PEDAL_PINS[i], INPUT_PULLUP);` : ""}
${e.i2c.length ? `  Wire.begin(${e.i2cPins?.sda ?? 1}, ${e.i2cPins?.scl ?? 2}, 400000);` : ""}
${m.oled.present ? `  oled.begin(SSD1306_SWITCHCAPVCC, 0x3C); drawStatus();` : ""}
  USB.begin();
  Kbd.begin(); Mouse.begin(); Consumer.begin();
}

void scanMatrix() {
  for (int c = 0; c < N_COLS; c++) {
    digitalWrite(COL_PINS[c], LOW);
    delayMicroseconds(12);
    for (int r = 0; r < N_ROWS; r++) {
      bool down = (digitalRead(ROW_PINS[r]) == LOW);
      if (down != keyState[r][c] && millis() - keyT[r][c] > DEBOUNCE_MS) {
        keyState[r][c] = down; keyT[r][c] = millis();
        tapCode(KEYMAP[profile][r][c], down);
      }
    }
    digitalWrite(COL_PINS[c], HIGH);
  }
}

void loop() {
  scanMatrix();
${e.encoders.length ? `  for (int i = 0; i < N_ENC; i++) {
    int8_t d = encDelta[i]; encDelta[i] = 0;
    while (d > 0) { d--; if (i == 0) { Consumer.press(CONSUMER_CONTROL_VOLUME_INCREMENT); Consumer.release(); } else Mouse.move(0, 0, 1); }
    while (d < 0) { d++; if (i == 0) { Consumer.press(CONSUMER_CONTROL_VOLUME_DECREMENT); Consumer.release(); } else Mouse.move(0, 0, -1); }
    static bool encSwWas[N_ENC] = {};
    bool sw = digitalRead(ENC_SW[i]) == LOW;
    if (sw && !encSwWas[i]) runMacro(i == 0 ? 7 : 5);
    encSwWas[i] = sw;
  }` : ""}
${m.pedals.count ? `  for (int i = 0; i < N_PEDALS; i++) {
    bool down = digitalRead(PEDAL_PINS[i]) == LOW;
    if (down != pedalState[i]) { pedalState[i] = down; tapCode(PEDAL_MAP[profile][i], down); }
  }` : ""}
${m.trackball.present ? `  static uint32_t tbT = 0;
  if (millis() - tbT > 8) { tbT = millis(); pollTrackball(); }` : ""}
${m.oled.present ? `  if (oledDirty) { oledDirty = 0; drawStatus(); }` : ""}
  delay(1);
}
`;
}

function buildKeymap(spec) {
  const e = spec.derived.elec;
  const R = e.matrix.rows.length, C = e.matrix.cols.length;
  // seed HID usage ids: a-z=4.., 1-9=30.., F13..F24=0x68.. — profiles vary slightly
  const seeds = [0x68, 0x04, 0x3A, 0x1E]; // gaming F13.., coding a.., editing F1.., business 1..
  let out = "";
  spec.profiles.forEach((p, pi) => {
    out += `  { // ${p.toUpperCase()}\n`;
    for (let r = 0; r < R; r++) {
      const cells = [];
      for (let c = 0; c < C; c++) {
        const key = e.matrix.keys.find(k => k.r === r && k.c === c);
        if (!key) { cells.push("0x00"); continue; }
        if (key.label === "VOICE") cells.push("MACRO_BASE+4");
        else if (key.label.startsWith("PC")) cells.push(`MACRO_BASE+${+key.label[2] - 1}`);
        else if (key.label === "KVM") cells.push("MACRO_BASE+3");
        else if (key.label === "OSD") cells.push("MACRO_BASE+5");
        else cells.push("0x" + ((seeds[pi % seeds.length] + r * C + c) & 0xff).toString(16).padStart(2, "0").toUpperCase());
      }
      out += `    { ${cells.join(", ")} },\n`;
    }
    out += "  },\n";
  });
  return out;
}

/** Crude C syntax highlighter for the firmware pane. */
export function highlightC(src) {
  return src
    .replace(/&/g, "&amp;").replace(/</g, "&lt;")
    .replace(/(\/\/[^\n]*)/g, '<span class="com">$1</span>')
    .replace(/("[^"]*")/g, '<span class="str">$1</span>')
    .replace(/\b(void|const|uint8_t|uint16_t|uint32_t|int8_t|int|bool|char|volatile|static|enum|return|if|else|for|while|switch|case|break|default|true|false|struct|delay|include|define)\b/g, '<span class="kw">$1</span>')
    .replace(/\b(0x[0-9A-Fa-f]+|\d+)\b/g, '<span class="num">$1</span>');
}
