/* NEXUS Observatory — scenario copilot.
   Grounding rule: the copilot only sees an evidence pack generated by the engine
   (outcomes, ranges, causal chains, assumptions). It is instructed to cite that
   evidence and to say "not modeled" rather than invent. A deterministic local
   brief generator provides the same structure without any API. */
(function () {
  const CP = (OBS.copilot = {});
  const KEY = "obs_api_key";
  // Shared Onehand OS key (rsg.anthropic_key) takes precedence; the local
  // obs_api_key remains a fallback for standalone use.
  CP.getKey = () => localStorage.getItem("rsg.anthropic_key") || localStorage.getItem(KEY) || "";
  CP.setKey = (k) => (k ? localStorage.setItem(KEY, k.trim()) : localStorage.removeItem(KEY));
  CP.enabled = () => !!CP.getKey();
  CP.lastError = null;

  // ---- outcome summarization (shared by UI, report, copilot) -----------
  // last-28-day (or post-start) medians & bands, deltas vs baseline
  CP.summarize = function (spec, results) {
    const win = Math.min(28, Math.floor(spec.horizonDays / 3));
    const tail = (arr) => { const t = arr.slice(-win).filter((v) => v != null); return t.length ? OBS.stat.mean(t) : null; };
    const out = { window: win, metrics: {}, watch: null };
    for (const m of spec.metrics) {
      const rows = {};
      for (const [bid, br] of Object.entries(results.branches)) {
        rows[bid] = { name: br.name, med: tail(br.agg[m].med), p10: tail(br.agg[m].p10), p90: tail(br.agg[m].p90) };
      }
      const base = rows.baseline?.med;
      for (const r of Object.values(rows)) r.delta = base != null && r.med != null ? r.med - base : null;
      out.metrics[m] = rows;
    }
    if (spec.watchOrg) {
      out.watch = {};
      for (const [bid, br] of Object.entries(results.branches)) {
        if (!br.watch) continue;
        const rev = tail(br.watch.med), lo = tail(br.watch.p10), hi = tail(br.watch.p90);
        out.watch[bid] = { name: br.name, revenue: rev, p10: lo, p90: hi, dailyCost: br.watch.dailyCost, margin: rev != null && br.watch.dailyCost != null ? rev - br.watch.dailyCost : null };
      }
    }
    return out;
  };

  CP.evidencePack = function (spec, results, sensitivity) {
    const s = CP.summarize(spec, results);
    const chains = {};
    for (const [bid, br] of Object.entries(results.branches)) {
      if (bid === "baseline") continue;
      chains[bid] = OBS.scenario.causalChains(br.repRun, 4).map((c) => flatten(c.tree, 0)).flat().slice(0, 18);
    }
    function flatten(node, depth) {
      return [({ day: node.day, depth, label: node.label })].concat(node.children.flatMap((ch) => flatten(ch, depth + 1)));
    }
    return {
      scenario: { name: spec.name, objective: spec.objective, horizonDays: spec.horizonDays, seeds: spec.seeds, headline: spec.headlineMetric },
      world: "Harborview District — fully synthetic demo world (" + OBS.app.world.population + " synthetic residents). Uncalibrated defaults unless noted.",
      outcome_window_days: s.window,
      metric_outcomes: s.metrics, new_business: s.watch,
      divergence: results.divergence,
      causal_chains: chains,
      assumptions: OBS.scenario.assumptionRows(spec, OBS.app.world).map((r) => `${r.label} = ${r.value}${r.unit ? " " + r.unit : ""} [${r.source}]`),
      notes: spec.assumptionsNotes, flags: spec.flags.map((f) => f.text),
      sensitivity: (sensitivity || []).map((r) => ({ driver: r.label, low: OBS.round(r.lo, 2), base: OBS.round(r.base, 2), high: OBS.round(r.hi, 2) })),
      reproducibility: results.meta,
    };
  };

  // ---- deterministic local brief --------------------------------------
  CP.localBrief = function (spec, results, sensitivity) {
    const s = CP.summarize(spec, results);
    const md = OBS.metricDef(spec.headlineMetric);
    const head = s.metrics[spec.headlineMetric] || {};
    const findings = [], risks = [];
    for (const [bid, r] of Object.entries(head)) {
      if (bid === "baseline" || r.med == null) continue;
      const dir = r.delta > 0 ? "higher" : "lower";
      const good = (md.better === "up") === (r.delta > 0);
      findings.push(`Under current assumptions, "${r.name}" ends the run with ${md.label.toLowerCase()} about ${md.fmt(Math.abs(r.delta))} ${dir} than baseline (median of ${spec.seeds} seeded runs; band ${md.fmt(r.p10)}–${md.fmt(r.p90)}). ${good ? "" : "This moves the headline metric in the unfavorable direction."}`);
    }
    for (const m of spec.metrics) {
      if (m === spec.headlineMetric) continue;
      const d = OBS.metricDef(m);
      for (const [bid, r] of Object.entries(s.metrics[m])) {
        if (bid === "baseline" || r.med == null || r.delta == null) continue;
        if (Math.abs(r.delta) > Math.abs(s.metrics[m].baseline?.med ?? 1) * 0.05) {
          findings.push(`${d.label}: ${r.name} differs from baseline by ${d.fmt(Math.abs(r.delta))} (${r.delta > 0 ? "higher" : "lower"}).`);
        }
      }
    }
    if (s.watch) {
      for (const [bid, w] of Object.entries(s.watch)) {
        if (w.revenue == null) continue;
        findings.push(`New business (${w.name}): modeled steady-state revenue ≈ ${OBS.fmt.money(w.revenue)}/day (range ${OBS.fmt.money(w.p10)}–${OBS.fmt.money(w.p90)}), vs ≈ ${OBS.fmt.money(w.dailyCost)}/day operating cost → estimated margin ${OBS.fmt.money(w.margin)}/day. ${w.margin < 0 ? "The model estimates this configuration does not break even." : ""}`);
      }
    }
    for (const [bid, dv] of Object.entries(results.divergence || {})) {
      if (dv.firstDay != null) risks.push(`Divergence from baseline begins around day ${dv.firstDay}${dv.firstEvents[0] ? `, opening with: "${dv.firstEvents[0].label}"` : ""}.`);
    }
    if (sensitivity?.length) risks.push(`The result is most sensitive to: ${sensitivity.slice(0, 3).map((r) => r.label).join("; ")}. A ±20% change in these materially moves the outcome.`);
    risks.push("All population behavior is synthetic and uncalibrated — treat magnitudes as directional, not predictive.");
    return {
      executive_summary: `Scenario "${spec.name}" was run over ${spec.horizonDays} days with ${spec.seeds} seeded Monte Carlo repetitions per branch against the synthetic Harborview baseline. The model estimates the effects below; ranges are P10–P90 across seeds. Results are conditional on the listed assumptions and should not be read as predictions.`,
      key_findings: findings.slice(0, 8),
      risks: risks,
      recommended_pilot: "Before acting on this simulation, validate the two most sensitive assumptions against real data (see sensitivity), and if possible run a small reversible pilot that mirrors the branch with the best risk-adjusted outcome.",
      monitoring: [md.label].concat((sensitivity || []).slice(0, 2).map((r) => "Real-world proxy for: " + r.label)),
      caveats: ["Synthetic population; no real individuals are represented.", "Uncalibrated engine defaults unless a calibration run has been applied.", "Second-order effects are modeled through explicit pathways only (see causal chains) — unmodeled channels exist."],
      generator: "local (deterministic)",
    };
  };

  // ---- Claude-backed brief --------------------------------------------
  const BRIEF_SCHEMA = {
    type: "object",
    properties: {
      executive_summary: { type: "string" },
      key_findings: { type: "array", items: { type: "string" } },
      risks: { type: "array", items: { type: "string" } },
      recommended_pilot: { type: "string" },
      monitoring: { type: "array", items: { type: "string" } },
      caveats: { type: "array", items: { type: "string" } },
    },
    required: ["executive_summary", "key_findings", "risks", "recommended_pilot", "monitoring", "caveats"],
    additionalProperties: false,
  };

  CP.request = async function (system, userContent, schema, maxTokens = 2500) {
    const model = OBS.store.data.settings.copilotModel || "claude-opus-4-8";
    const messages = [{ role: "user", content: userContent }];
    // Shared portfolio bridge when present (Fable-5 fallback beta, refusal
    // detection, structured outputs); inline fetch keeps standalone working.
    if (window.RSGClaude) {
      const { text } = await window.RSGClaude.request({ key: CP.getKey(), model, system, messages, schema, maxTokens });
      return JSON.parse(text);
    }
    const res = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "content-type": "application/json", "x-api-key": CP.getKey(),
        "anthropic-version": "2023-06-01", "anthropic-dangerous-direct-browser-access": "true",
      },
      body: JSON.stringify({
        model,
        max_tokens: maxTokens, system,
        messages,
        output_config: { format: { type: "json_schema", schema } },
      }),
    });
    if (!res.ok) { const e = await res.json().catch(() => ({})); throw new Error(e?.error?.message || "API " + res.status); }
    const data = await res.json();
    if (data.stop_reason === "refusal") throw new Error("model declined");
    const block = (data.content || []).find((b) => b.type === "text");
    return JSON.parse(block.text);
  };

  CP.brief = async function (spec, results, sensitivity) {
    const evidence = CP.evidencePack(spec, results, sensitivity);
    const system = `You are the analysis copilot inside NEXUS Observatory, a simulation platform. You will receive an EVIDENCE PACK produced by a deterministic simulation engine.

Rules — non-negotiable:
- Every claim must trace to the evidence pack. Cite concrete numbers from it. Do not invent data, agents, events, or effects the pack does not contain.
- The world is synthetic and uncalibrated; use hedged language ("the model estimates…", "under current assumptions…"). Never say an outcome "will" happen.
- If the pack lacks something needed to answer, state that it was not modeled.
- Quantities carry P10–P90 ranges across seeded runs — report ranges, not just point values.
- Audience: business/operations/planning decision-makers. Plain language, no hype.`;
    const out = await CP.request(system, "EVIDENCE PACK:\n" + JSON.stringify(evidence, null, 1), BRIEF_SCHEMA, 3000);
    out.generator = "copilot (" + (OBS.store.data.settings.copilotModel || "claude-opus-4-8") + ")";
    return out;
  };

  // ---- Claude-backed NL scenario parse --------------------------------
  const PARSE_SCHEMA = {
    type: "object",
    properties: {
      name: { type: "string" }, objective: { type: "string" },
      horizonDays: { type: "integer" }, headlineMetric: { type: "string", enum: ["unemployment_rate", "labor_income", "consumer_spend", "external_leakage", "retail_revenue", "avg_commute", "congestion_index", "grocery_access", "clinic_wait", "clinic_lost", "productivity_loss", "closures_cum"] },
      branches: {
        type: "array",
        items: {
          type: "object",
          properties: {
            name: { type: "string" },
            deltas: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  type: { type: "string", enum: ["close_road", "outage", "layoff", "open_business", "price_change", "facility_config", "add_housing", "demand_shock", "param"] },
                  edgeId: { type: ["string", "null"] }, subId: { type: ["string", "null"] }, orgId: { type: ["string", "null"] },
                  nb: { type: ["string", "null"] }, sector: { type: ["string", "null"] }, name: { type: ["string", "null"] },
                  pct: { type: ["number", "null"] }, count: { type: ["integer", "null"] }, units: { type: ["integer", "null"] },
                  category: { type: ["string", "null"] }, key: { type: ["string", "null"] }, value: { type: ["number", "null"] },
                  priceLevel: { type: ["number", "null"] }, quality: { type: ["number", "null"] }, capacityDaily: { type: ["integer", "null"] },
                  staff: { type: ["integer", "null"] }, wage: { type: ["number", "null"] },
                  config: { type: ["object", "null"], properties: { servers: { type: ["integer", "null"] }, layoutEff: { type: ["number", "null"] }, triage: { type: ["boolean", "null"] } }, additionalProperties: false },
                  startDay: { type: ["integer", "null"] }, days: { type: ["integer", "null"] },
                },
                required: ["type"], additionalProperties: false,
              },
            },
          },
          required: ["name", "deltas"], additionalProperties: false,
        },
      },
      unmapped: { type: "array", items: { type: "string" }, description: "Aspects of the request the modeled levers cannot represent" },
      inferred_assumptions: { type: "array", items: { type: "string" }, description: "Every default or guess made — each requires user review" },
    },
    required: ["name", "objective", "horizonDays", "headlineMetric", "branches", "unmapped", "inferred_assumptions"],
    additionalProperties: false,
  };

  CP.parseScenario = async function (text) {
    const world = OBS.app.world;
    const catalog = {
      roads: world.graph.byType("road").map((r) => ({ id: r.id, name: r.name })),
      neighborhoods: world.graph.byType("neighborhood").map((n) => ({ id: n.id, name: n.name })),
      organizations: world.graph.byType("organization").map((o) => ({ id: o.id, name: o.name, sector: o.attrs.sector, jobs: o.attrs.jobs })),
      substations: [{ id: "sub_north", serves: "Northfield, Midtown" }, { id: "sub_south", serves: "Harbor Point, Old Row, Eastgate, Westside Industrial" }],
      sectors: ["grocery", "dining", "retail", "services", "fitness", "healthcare"],
      params: OBS.world.PARAMS.map((p) => p.key),
    };
    const system = `You translate a plain-language decision question into a structured simulation scenario for the Harborview synthetic world. Use ONLY entity ids from the provided catalog. Map the request to the available delta types; anything unmappable goes in "unmapped" (do NOT approximate silently). List EVERY default you choose in "inferred_assumptions". Branches: create multiple when the user compares options; otherwise one intervention branch (a no-change baseline is added automatically). startDay defaults to 8 (one week of warm-up).`;
    const out = await CP.request(system, "CATALOG:\n" + JSON.stringify(catalog) + "\n\nREQUEST:\n" + text, PARSE_SCHEMA, 2000);
    const spec = OBS.scenario.newSpec({
      name: out.name, objective: out.objective || text, horizonDays: OBS.clamp(out.horizonDays || 90, 14, 400),
      headlineMetric: out.headlineMetric,
      branches: out.branches.map((b, i) => ({ id: "b" + (i + 1), name: b.name, deltas: b.deltas.map(clean) })),
    });
    spec.flags = out.unmapped.map((u) => ({ level: "blocked", text: "Not modeled: " + u }))
      .concat(out.inferred_assumptions.map((a) => ({ level: "review", text: a })));
    if (spec.branches.some((b) => b.deltas.some((d) => d.type === "open_business"))) {
      spec.watchOrg = "newbiz";
      for (const b of spec.branches) for (const d of b.deltas) if (d.type === "open_business") d.orgId = "newbiz";
    }
    function clean(d) { const o = {}; for (const [k, v] of Object.entries(d)) if (v != null) o[k] = v; if (o.startDay == null) o.startDay = 8; return o; }
    return spec;
  };
})();
